ALTER TABLE users ADD COLUMN IF NOT EXISTS yandex_login VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS yandex_display_name VARCHAR(255);
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS birthdate DATE;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS yandex_phone VARCHAR(50);